# Generated by Django 4.1.3 on 2022-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybug', '0004_auto_20200728_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
